### ISSUE TITLE
 setting not set

### ISSUE THREAD

**Issue by Samraw003** [jeffreykemp/mailgun-plsql-api#43]
On running mailgun_pkg.email_is_valid I am encountering the following error:

Error report -
ORA-20000: mailgun setting not set "pubkey-xxxxxxxxxxxxxxxxxxxxxxx" - please setup using MAILGUN_PKG.init()

Additionally,

on executing     mailgun_pkg.push_queue I encountered the following error:
ORA-20000: mailgun setting not set "app.optimium.in" - please setup using MAILGUN_PKG.init()

I have noted down the API keys from mailgun.

**Comment by jeffreykemp** [comment]
Can you please confirm that you have not made ANY changes to the package code?

**Comment by Samraw003** [comment]
Hi Jeff,

Apologies, I didn't follow the instructions!

Regards

**Comment by jeffreykemp** [comment]
No problem.

The constants in the package are for internal use only and shouldn't be modified.

Thanks
